# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/liangxiaoshi666/kernel_xiaomi_sm8350-miui
          kernel-dir: msm-5.4
          kernel-branch: miui-t
          config: renoir_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-other: true
          ksu-url: https://github.com/rsuntk/KernelSU
          ksu-version: main
          android-version: 12
          aosp-clang-version: r487747c
          disable-lto: true
          anykernel3: true
